#!/bin/sh


install_dir=`dirname $0`
/usr/sbin/installer -dumplog -verbose -pkg $install_dir/"CMClient.pkg" -target "$3"
/usr/sbin/installer -dumplog -verbose -pkg $install_dir/"CMEnroll.pkg" -target "$3"


exit 0